# To create all microservices without own Spring's logs: docker-compose up -d
# To start existing all microservices without own Spring's logs: docker-compose start -d

# To stop all microservices: docker-compose stop
# To stop and remove all microservices: docker-compose down

services:
  accounts:
    image: kent0k/accounts:s4
    container_name: accounts-microservice
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kent0kmicroservicesharednetwork

  loans:
    image: kent0k/loans:s4
    container_name: loans-microservice
    ports:
      - 8082:8090
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kent0kmicroservicesharednetwork

  cards:
    image: kent0k/cards:s4
    container_name: cards-microservice
    ports:
      - 8083:9000
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kent0kmicroservicesharednetwork

networks:
  kent0kmicroservicesharednetwork:
    driver: bridge