services:
  network-deploy-service:
    networks:
      - kent0kmicroservicesharednetwork

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-spring-app

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver-container:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver-container:8071/