
FROM eclipse-temurin:21-jdk

MAINTAINER eazybytes.com

COPY build/libs/gatewayserver-0.0.1-SNAPSHOT.jar gatewayserver-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "gatewayserver-0.0.1-SNAPSHOT.jar"]
