global:
  configMapName: eazybankprod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
  dbName: mysql
  dbPort: 3306
  sshVolumeName: ssh-volume
  sshHostPathFolder: "/run/desktop/mnt/host/wsl/docker-desktop-data/version-pack-data/community/docker/volumes/ssh-volume/_data"
  sshContainerPathFolder: "/root/.ssh"
