# To create all microservices without own Spring's logs: docker-compose up -d
# To start existing all microservices without own Spring's logs: docker-compose start -d

# To stop all microservices: docker-compose stop
# To stop and remove all microservices: docker-compose down

services:

# Hookdeck is need to set up auto trigger 'localhost' endpoint. More: github webhooks.
  hookdeck:
    image: hookdeck/hookdeck-cli:latest
    entrypoint: [ "/bin/sh","-c" ]
    stdin_open: true
    tty: true
    command:
# We need to run these two commands manually in EXEC in Docker hookdeck container
      - |
        hookdeck login --cli-key 4dd16gfai1ay12nkfuo62any7ymzr7i8cor0czbaabgyx4tupw
        hookdeck listen 8071 Source
# Next please input '/monitor' and after that 'configserver-container'
    extends:
      file: common-config.yml
      service: network-deploy-service

  rabbit:
    image: rabbitmq:3.12-management
    container_name: rabbit
    hostname: rabbitmq-spring-app
    ports:
      - 5672:5672
      - 15672:15672
    extends:
      file: common-config.yml
      service: network-deploy-service
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis-container:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    extends:
      file: common-config.yml
      service: network-deploy-service
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  configserver-container:
    image: kent0k/configserver:s10
    container_name: configserver-microservice
    ports:
      - 8071:8071
    extends:
      file: common-config.yml
      service: microservice-base-config
    deploy:
      resources:
        limits:
          memory: 700m
    volumes:
      - ./../ssh_keys:/home/cnb/.ssh # we need manually add ssh keys from host OS to 'ssh_keys' folder to pass host ssh keys to local docker container to assume that GIT cloud config will work
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy

  eurekaserver-container:
    image: kent0k/eurekaserver:s10
    container_name: eurekaserver-microservice
    ports:
      - 8070:8070
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  gatewayserver-container:
    image: kent0k/gatewayserver:s10
    container_name: gatewayserver-microservice
    ports:
      - 8072:8072
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    deploy:
      resources:
        limits:
          memory: 500m
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis-container
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis-container:
        condition: service_healthy

  accountsdb-container:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  loansdb-container:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  cardsdb-container:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  accounts:
    image: kent0k/accounts:s10
    container_name: accounts-microservice
    ports:
      - 8081:8080
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb-container:3306/accountsdb
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      accountsdb-container:
        condition: service_healthy

  loans:
    image: kent0k/loans:s10
    container_name: loans-microservice
    ports:
      - 8082:8090
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb-container:3306/loansdb
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      loansdb-container:
        condition: service_healthy

  cards:
    image: kent0k/cards:s10
    container_name: cards-microservice
    ports:
      - 8083:9000
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb-container:3306/cardsdb
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cardsdb-container:
        condition: service_healthy

networks:
  kent0kmicroservicesharednetwork:
    driver: bridge